# Generated by Django 5.0.6 on 2024-07-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(max_length=20)),
                ('class_abbr', models.CharField(max_length=50)),
                ('class_range', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'class_list',
            },
        ),
    ]
