# Generated by Django 5.0.6 on 2024-07-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlist',
            name='class_abbr',
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='class_range',
        ),
        migrations.AddField(
            model_name='classlist',
            name='class_level_abbr',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classlist',
            name='classno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='class_level',
            field=models.CharField(max_length=50),
        ),
    ]
