# Generated by Django 5.0.6 on 2024-07-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_remove_classlist_class_abbr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_Q', models.FileField(upload_to='\\quizdocs')),
                ('audio_Q', models.FileField(upload_to='\\quizdocs')),
                ('video_Q', models.FileField(upload_to='\\quizdocs')),
                ('updated_on', models.DateTimeField()),
                ('classId', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, to='Quiz.classlist')),
            ],
            options={
                'db_table': 'quiz_master',
            },
        ),
    ]
